version: '{build}'
branches:
  only:
    - master
skip_tags: true
max_jobs: 1
image: Visual Studio 2017
environment:
  api_key:
    secure: P2UXmKs8zxTlRnQsSZiE1awkrPzmRoKLdpYiM5NZqmbq7KBylaBOVFcg7JvVi/dD
install:
  - cmd: git submodule update --init --recursive
build_script:
  - ps: .\update-all.ps1 -Push
